# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('iD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('creditCard', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingPoint', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Person')),
            ],
        ),
    ]
